version: 2

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip libeigen3-dev
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install -r test_requirements.txt
      - run: pip3 install .
      # lint
      - run: pylint setup.py accupy/ test/*.py
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --cov accupy
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
